### ISSUE TITLE
Plz, upgrage the package on the NPM

### ISSUE THREAD

**Issue by maxkoryukov** [thirus/gulp-csslint-report#6]
Hello!

Don't know how to get in touch with you, but plz, update the package on NPM... 

Even documentation on NPM is out of date (empty page ;)

**Comment by thirus** [comment]
Thanks for your interest! 
Will update the NPM when I get sometime later today.

**Comment by maxkoryukov** [comment]
Cool!
Thank you for superfast update;) NPM updated :octocat: !!
